language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="b1051061-6f8b-45d2-a835-a93b8e63975b"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - voronovadaria@gmail.com
    on_success: never # default: change
    on_failure: always # default: always